backend:
  name: git-gateway
  branch: master
  repo: chandramoli/glowdesi

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "public/content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: "layout"
        label: "Layout"
        widget: "hidden"
        default: "posts"
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "date"
        label: "Date"
        widget: "date"
        date_format: "YYYY-MM-DD"
        time_format: false
      - name: "thumbnail"
        label: "Featured Image"
        widget: "image"
      - name: "body"
        label: "Body"
        widget: "markdown"
